name: Retry Test
on:
  workflow_run:
    workflows: ['Test']
    branches: [master]
    types:
      - completed
  workflow_dispatch:

jobs:
  retry:
    name: Retry test
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 6 }}
    strategy:
      matrix:
        node: [14.x]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: View
        uses: actions/github-script@v5
        with:
          script: console.log(context)
      - name: View
        uses: actions/github-script@v5
        with:
          script: console.log(github)
      - name: Log attempt
        run: echo "Attempt no ${{ github.event.workflow_run.run_attempt }}"
      - name: Retry workflow
        uses: actions/github-script@v5
        with:
          script: |
            github.request('POST ' + context.payload.workflow_run.rerun_url)

