name: Retry Test
on:
    :
    workflows: ['Test']
    branches: [master]
    types:
      - completed
  workflow_dispatch:

jobs:
  retry:
    name: Retry test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: View 
        uses: actions/github-script@v5
        with:
          script: console.log(github.event.workflow_run)
